### ISSUE TITLE
dist/ missing in 1.2.4?

### ISSUE THREAD

**Issue by darcywong00** [Glowstudent777/YouVersion-API-NPM#4]
Sorry to disturb you.
When I try to install the latest version
```bash
 npm i @glowstudent/youversion@1.2.4
```

the dist/ folder is missing compared to
```bash
 npm i @glowstudent/youversion@1.2.3
```

Am I missing a step in the installation?

**Comment by Glowstudent777** [comment]
I'll take a look at it

**Comment by Glowstudent777** [comment]
It appears it's not publishing the built directory. I'll have to fix the script and I'll have it re published soon

**Comment by Glowstudent777** [comment]
Hi, sorry for the wait, first time using a workflow to automate NPM package publishing. The newest version is v1.2.6 due to not being able to overide existing versions on NPM. The problem should be resolved in this release.

Thank you for your patience and happy coding!
