### ISSUE TITLE
Verse of the Day Returning Bible.com Footer

### ISSUE THREAD

**Issue by grapemoli** [Glowstudent777/YouVersion-API-NPM#7]
Hi! I apologize in advance if anything is wrong--I'm new to this! 

I used the exact same code in the docs, and ran across a problem.

<br>

**Expected Behavior**
`{
  citation: 'John 13:14 (NIV)',
  passage: 'Now that I, your Lord and Teacher, have washed your feet, you also should wash one another’s feet.'
}
`

<br>

**Actual Behavior**
The module kept returning the wrong passage:
`{
  citation: 'John 13:14 (NIV)', 
  passage: 'Encouraging and challenging you to seek intimacy with God every day.'
}
`

<br>

**Problem**
In the VOTD typescript, I saw that you got the passage from `p.text-gray-50`.  Upon inspection of BIble.com, I found that multiple elements correlate to this class. One of them is the footer:

<img width="474" alt="Screenshot 2024-03-27 at 8 52 14 PM" src="https://github.com/Glowstudent777/YouVersion-API-NPM/assets/105399768/513ca9cb-f846-43d9-ae7a-039149183e3c">

<br>

**Solution**
I'm not sure. Maybe fetch the outer div `mbs-3 border border-l-large border-black pli-1 plb-1 pis-2`, and then fetching the `p.text-gray-50`. As far as observations go, only the VOTD is wrapped in the `mbs-3` outer div.

**Comment by Glowstudent777** [comment]
Thanks for letting me know, I'll get that fixed shortly

**Comment by Glowstudent777** [comment]
Should be fixed. Please upgrade to version 1.3.0.

![snippet](https://github.com/Glowstudent777/YouVersion-API-NPM/assets/55334764/44f3582b-b324-4ddf-9bcf-7c860a726dd9)

**Comment by grapemoli** [comment]
It's working perfectly, thank you! ✨
